---
apiVersion: v1
kind: Service
metadata:
  annotations:
    demo.redhat.com/vcs-url: https://github.com/rhtevan/microsweeper-quarkus.git
    app.openshift.io/vcs-url: <<unknown>>
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: microsweeper-appservice
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    demo.redhat.com/name: microsweeper
    app.openshift.io/runtime: quarkus
  name: microsweeper-appservice
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: microsweeper-appservice
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    demo.redhat.com/vcs-url: https://github.com/rhtevan/microsweeper-quarkus.git
    app.openshift.io/vcs-url: <<unknown>>
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: microsweeper-appservice
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    demo.redhat.com/name: microsweeper
    app.openshift.io/runtime: quarkus
  name: microsweeper-appservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: microsweeper-appservice
  template:
    metadata:
      annotations:
        demo.redhat.com/vcs-url: https://github.com/rhtevan/microsweeper-quarkus.git
        app.openshift.io/vcs-url: <<unknown>>
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: microsweeper-appservice
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        demo.redhat.com/name: microsweeper
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: to-be-replaced
          imagePullPolicy: Always
          name: microsweeper-appservice
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgresql
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-1
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.3-0
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 1
  port: 5432
  postgresVersion: 14
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    demo.redhat.com/vcs-url: https://github.com/rhtevan/microsweeper-quarkus.git
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: microsweeper-appservice
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    demo.redhat.com/name: microsweeper
    app.openshift.io/runtime: quarkus
  name: microsweeper-appservice
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: microsweeper-appservice
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: microsweeper-appservice-postgresql
spec:
  application:
    group: apps
    name: microsweeper-appservice
    version: v1
    kind: Deployment
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgresql
  detectBindingResources: false
  bindAsFiles: true
