---
################################################################################
# The KRMs in this yaml file are used by quarkus openshift extension for 
# customizing local deployment to a DEV cluster/environment with a quarkus
# command like: 
#   quarkus build --no-tests -Dquarkus.kubernetes.deploy=true
# That manual test deployment should happen before a commit & push to github
# which will then trigger a CI/CD pipeline to build and deployment application to
# a TEST cluster/environment
################################################################################# 
# PostgreSQL DB CR (Bindable Operator)
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgresql
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.3-0
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    name: instance1
    replicas: 1
  port: 5432
  postgresVersion: 14
...