apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microsweeper-quarkus
  namespace: openshift-gitops
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: env/prod
    repoURL: https://github.com/rhtevan/microsweeper-quarkus.git
    targetRevision: HEAD
  syncPolicy: {}
